Adding the dropdown fixes for the header and comments for each functions
ELEVATE-Project/self-creation-portal pull request #184
Opened 2024-09-02 11:25 UTC by Arti-Khillare1

2024-09-04 12:34 UTC, ramkumar-pacewisdom requested changes

2024-09-04 12:34 UTC, ramkumar-ns-dev commented on projects/lib-shared-modules/src/lib/components/dialogs/dialog-model/dialog-model.component.scss
> +    font-size: 12px;
why it's in 12px ?

2024-09-04 12:34 UTC, ramkumar-ns-dev commented on projects/lib-shared-modules/src/lib/components/dialogs/dialog-model/dialog-model.component.scss
>  .error-message{
please change all px to rem

2024-09-06 13:14 UTC, ramkumar-pacewisdom requested changes

2024-09-06 13:14 UTC, ramkumar-pacewisdom commented on projects/self-creation-portal/src/app/components/resource-holder/resource-holder.component.ts
>    onPageChange(event: any) {
bro this function not returning anything.

2024-09-10 07:59 UTC, merged