card and search functionality
ELEVATE-Project/self-creation-portal pull request #5
Opened 2024-05-06 07:55 UTC by GSuma21

2024-05-06 08:36 UTC, ramkumar-pacewisdom requested changes

2024-05-06 08:36 UTC, ramkumar-pacewisdom commented on projects/lib-shared-modules/src/lib/components/search/search.component.ts
>  export class SearchComponent {
Please add 
1. debouce timers.
2. minimum characters length property for search (Characters length should comes from parent and it's also should have default value if it's not passed from parent )

2024-05-06 08:36 UTC, ramkumar-ns-dev commented on projects/lib-shared-modules/src/lib/components/search/search.component.ts
> +    this.searchEvent.emit(searchText);
is this will detect the text changes automatically and emit the data ?

2024-05-06 08:36 UTC, ramkumar-ns-dev commented on projects/self-creation-portal/src/app/app.component.ts
> +
I can see it's an emitter from search component, if emitter works, please remove the empty function.

2024-05-10 04:09 UTC, ramkumar-ns-dev commented on projects/lib-shared-modules/src/lib/components/search/search.component.html
> +    <input matInput #searchInput required [formControl]="searchControl" [attr.maxlength]="maxLength"  (keyup.enter)="search(searchInput.value)" placeholder="Search" >
why "required" attribute added here ?
And do we need form Control here ?

2024-05-10 04:16 UTC, GSuma21 commented on projects/lib-shared-modules/src/lib/components/search/search.component.html
> +    <input matInput #searchInput required [formControl]="searchControl" [attr.maxlength]="maxLength"  (keyup.enter)="search(searchInput.value)" placeholder="Search" >
form control is required while using debounce time ,
required is validation of input

2024-05-13 03:27 UTC, ramkumar-pacewisdom approved these changes

2024-05-13 09:15 UTC, merged