Adding delete api integration for drafts page and submit-for-review with updated figma.
ELEVATE-Project/self-creation-portal pull request #88
Opened 2024-07-10 04:45 UTC by Arti-Khillare1

2024-07-10 05:54 UTC, ramkumar-pacewisdom requested changes

2024-07-10 05:54 UTC, ramkumar-pacewisdom commented on projects/lib-project/src/lib/lib-project.service.ts
> +        console.log('Delete project successsfully', result);
Aren't there any toaster after project deleted successfully?

2024-07-10 05:54 UTC, ramkumar-pacewisdom commented on projects/self-creation-portal/src/app/components/resource-holder/resource-holder.component.ts
> +import { DialogPopupComponent } from '../../../../../lib-shared-modules/src/public-api';
Why this import like this, not from library ?

2024-07-10 05:54 UTC, ramkumar-pacewisdom commented on projects/self-creation-portal/src/app/components/resource-holder/resource-holder.component.ts
> +import { DialogPopupComponent } from '../../../../../lib-shared-modules/src/public-api';
Please change all other places as well.

2024-07-10 06:55 UTC, Arti-Khillare1 commented on projects/lib-project/src/lib/lib-project.service.ts
> +        console.log('Delete project successsfully', result);
No there is no any toaster after project delete in figma I checked

2024-07-11 06:56 UTC, ramkumar-pacewisdom approved these changes

2024-07-11 07:47 UTC, merged