updated delete api with the previous page issue fixed after deleting …
ELEVATE-Project/self-creation-portal pull request #93
Opened 2024-07-15 12:36 UTC by Arti-Khillare1

…all project

2024-07-15 12:52 UTC, ramkumar-pacewisdom requested changes

2024-07-15 12:52 UTC, ramkumar-ns-dev commented on projects/lib-project/src/lib/lib-project.service.ts
> +  deleteProject(projectId:number|string,projectData:any){
why project in payload ?

2024-07-15 12:52 UTC, ramkumar-ns-dev commented on projects/lib-shared-modules/src/lib/services/http-provider.service.ts
> +    delete(endpoint: string, options?: { headers?: HttpHeaders, params?: HttpParams, body?: any }) {
why body for delete ?

2024-07-16 05:40 UTC, ramkumar-pacewisdom approved these changes

2024-07-16 05:40 UTC, merged